# Generated by Django 6.0.6 on 2026-07-22 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(upload_to='gifts/')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=550)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('lang_code', models.CharField(default='ru', max_length=10)),
                ('is_banned', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_turnover'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gift')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardPerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('deposited', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_per_month', to='users.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='users.telegramuser'),
        ),
    ]
