# Generated by Django 6.0.6 on 2026-07-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='ref_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='total_earned_from_referrals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='balance',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=20),
        ),
    ]
