# Generated by Django 6.0.6 on 2026-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_ref_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='channel_sub_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='chat_sub_done',
            field=models.BooleanField(default=False),
        ),
    ]
