# Generated by Django 6.0.6 on 2026-07-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_telegramuser_channel_sub_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='ref_id',
            field=models.IntegerField(null=True),
        ),
    ]
