# Generated by Django 6.0.6 on 2026-08-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegramuser_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
    ]
