# Generated by Django 6.0.6 on 2026-08-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_telegramuser_total_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
