# Generated by Django 6.0.6 on 2026-08-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_telegramuser_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='image',
        ),
        migrations.AddField(
            model_name='gift',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
