# Generated by Django 6.0.6 on 2026-08-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_gift_image_gift_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='total_earned',
        ),
    ]
