# Generated by Django 6.0.6 on 2026-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_telegramuser_total_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_forward_task_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_free_case_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
