# Generated by Django 6.0.6 on 2026-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_telegramuser_last_forward_task_done_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
