# Generated by Django 6.0.6 on 2026-08-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0010_telegramuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawals',
            name='gift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='users.gift'),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='users.telegramuser'),
        ),
    ]
