# Generated by Django 6.0.6 on 2026-08-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_withdrawals_gift_alter_withdrawals_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawals',
            name='admin_messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('closed', 'Закрыт'), ('rejected', 'Отклонён')], default='pending', max_length=50),
        ),
    ]
