# Generated by Django 6.0.6 on 2026-08-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0008_remove_telegramuser_total_earned'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.case')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='users.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='games_caseo_created_b2f56b_idx')],
            },
        ),
    ]
